name: Docker Build Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t rithickdev/taskflow-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t rithickdev/taskflow-frontend:latest ./frontend

      - name: Push backend image
        run: docker push rithickdev/taskflow-backend:latest

      - name: Push frontend image
        run: docker push rithickdev/taskflow-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devops-taskflow
            docker compose pull
            docker compose up -d
            docker image prune -f
